### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by olepg** [Road-block/Cartographer_Herbalism#1]
addon.lua:414: attempt to index field L (a nil value)

Got this error first time I loaded the addon. is it broken?

**Comment by Road-block** [comment]
You are probably trying to use this with a different core Cartographer addon.

Try getting the full package from [here](https://github.com/Road-block/Cartographer/releases/latest)
at Downloads.

**Comment by Road-block** [comment]
No response so I'm guessing that was the cause

**Comment by olepg** [comment]
Sorry, was out.
Yes that was the cause. Thank you very much Road-block.
